# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_test1(self):
    self.driver.get("https://demoqa.com/")
    self.driver.set_window_size(1013, 840)
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(1) .card-up").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-6").click()
    self.driver.find_element(By.CSS_SELECTOR, ".show #item-0 > .text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".show #item-1 > .text").click()
    self.driver.switch_to.frame(3)
    self.driver.switch_to.frame(0)
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".JPG > image").click()
    self.vars["win1294"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win1294"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
  
